#2 Numbers and Math
print("#2 Numbers and Math")
print("Now we'll move on to the basic algebra in Python 3 ")
print("This line will be followed by the result of 3+4 :",3+4)
print("This line will be followed by the result of 24*7 :",24*7)
print("This line will be followed by a long algebraic operation in order of PEMDAS 3 +2 +1 -5 +4 %2 -1 /4 *6 :",3 +2 +1 -5 +4 %2 -1 /4 *6)
print("This line will be followed by the result of 3>5 in boolean manner :",3>5)
print("3>-5 :",3>-5)
print("3<=3 :",3<=3)
print("3<=-3 :",3<=-3)
print("3==-3 :",3==-3)
print("3==3 :",3==3)
